"""Shared helpers for the sprite tools.

crop_frames.py (collage/panel sheets) and slice_grid.py (Nano Banana pose
grids) both write into assets/sprites/. The manifest lists whatever PNGs
are there, so the two tools never fight over who owns the SPRITES map --
each just writes its own strips and rebuilds the listing.
"""
from pathlib import Path


def _entries(root: Path, sub: str):
    d = root / "assets" / sub
    names = sorted(p.stem for p in d.glob("*.png")) if d.exists() else []
    return names, "\n".join(f"  '{n}': './assets/{sub}/{n}.png'," for n in names)


def write_manifest(root: Path):
    """Regenerate src/assets-manifest.js from assets/sprites/ (SPRITES) and
    assets/tiles/ (TILES). build.mjs inlines only the referenced ones."""
    snames, slines = _entries(root, "sprites")
    tnames, tlines = _entries(root, "tiles")
    manifest = root / "src" / "assets-manifest.js"
    manifest.write_text(
        "// GENERATED by tools/ (crop_frames.py, slice_grid.py, slice_tiles.py) — do not edit.\n"
        "// Lists every PNG in assets/sprites and assets/tiles; build.mjs inlines the\n"
        "// referenced ones as data URIs.\n"
        f"export const SPRITES = {{\n{slines}\n}};\n\n"
        f"export const TILES = {{\n{tlines}\n}};\n"
    )
    return manifest, len(snames) + len(tnames)
