"""Shared helpers for the sprite tools.

crop_frames.py (collage/panel sheets) and slice_grid.py (Nano Banana pose
grids) both write into assets/sprites/. The manifest lists whatever PNGs
are there, so the two tools never fight over who owns the SPRITES map --
each just writes its own strips and rebuilds the listing.
"""
from pathlib import Path


def write_manifest(root: Path):
    """Regenerate src/assets-manifest.js from the PNGs in assets/sprites/."""
    sprites = root / "assets" / "sprites"
    names = sorted(p.stem for p in sprites.glob("*.png"))
    lines = "\n".join(f"  '{n}': './assets/sprites/{n}.png'," for n in names)
    manifest = root / "src" / "assets-manifest.js"
    manifest.write_text(
        "// GENERATED by tools/crop_frames.py + tools/slice_grid.py — do not edit.\n"
        "// Lists every strip in assets/sprites/; build.mjs inlines the referenced\n"
        "// ones as data URIs.\n"
        f"export const SPRITES = {{\n{lines}\n}};\n"
    )
    return manifest, len(names)
