// Dev static server with caching disabled. Chrome's heuristic caching of ES
// modules can otherwise leave a freshly edited page running a MIX of old and
// new modules — bugs that exist in no version of the code. No dependencies.

import { createServer } from 'node:http';
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { extname, join, normalize, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';
import { renderText, manifests } from './dump-map.mjs';

const root = fileURLToPath(new URL('.', import.meta.url));
const port = Number(process.env.PORT ?? 8060);

const json = (res, obj, code = 200) => {
  res.writeHead(code, { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' });
  res.end(JSON.stringify(obj));
};
const readBody = async (req) => {
  const chunks = [];
  for await (const c of req) chunks.push(c);
  return chunks.length ? JSON.parse(Buffer.concat(chunks).toString('utf8')) : {};
};
// Run the Python tile slicer and return its stdout.
const runSlicer = (args) =>
  new Promise((resolve, reject) => {
    const p = spawn('python3', [join(root, 'tools', 'slice_tiles.py'), ...args], { cwd: root });
    let out = '', err = '';
    p.stdout.on('data', (d) => (out += d));
    p.stderr.on('data', (d) => (err += d));
    p.on('close', (code) => (code === 0 ? resolve(out) : reject(new Error(err || `exit ${code}`))));
  });
const safeName = (s) => String(s).replace(/[^a-z0-9-]/gi, '').toLowerCase();

// serve.mjs statically imports ZONES/PLACEMENTS via dump-map.mjs, and Node caches
// that import — so after we rewrite a data file on disk we re-import it with a
// cache-busting query to read the fresh version back (used to keep maps.txt/json
// in step after a geometry edit, no server restart needed).
const freshZones = async () => (await import('./data/zones.js?v=' + Date.now())).ZONES;
const freshPlacements = async () => (await import('./data/placements.js?v=' + Date.now())).PLACEMENTS;

// Surgically swap one subregion's `map: [...]` array in the zones.js source,
// leaving every other line (comments, tables, bosses) byte-for-byte intact.
// zones.js is hand-authored, so this validates hard and never partially writes:
// rows must be equal-length strings of legal map chars with exactly one start.
const MAP_ROW = /^[#.SE1-9]+$/;
function rewriteZonesMap(source, subId, rows) {
  if (!Array.isArray(rows) || rows.length === 0) throw new Error(`${subId}: empty map`);
  const w = rows[0].length;
  for (const r of rows) {
    if (typeof r !== 'string' || r.length !== w) throw new Error(`${subId}: map rows must be equal-length strings`);
    if (!MAP_ROW.test(r)) throw new Error(`${subId}: illegal character in row "${r}"`);
  }
  const starts = rows.join('').match(/S/g)?.length ?? 0;
  if (starts !== 1) throw new Error(`${subId}: map needs exactly one S (found ${starts})`);
  const esc = subId.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  // map strings contain no ']', so [\s\S]*? runs to the array's closing bracket.
  const re = new RegExp(`(id:\\s*['"]${esc}['"][\\s\\S]*?map:\\s*\\[)[\\s\\S]*?(\\])`);
  if (!re.test(source)) throw new Error(`${subId}: could not locate its map[] in zones.js`);
  const block = '\n' + rows.map((r) => `          '${r}',`).join('\n') + '\n        ';
  return source.replace(re, (_, open, close) => open + block + close);
}

const TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json',
  '.png': 'image/png',
  '.svg': 'image/svg+xml',
};

createServer(async (req, res) => {
  try {
    const url = new URL(req.url, 'http://localhost');

    // ---- tile editor endpoints (dev-only, same-origin localhost) ----
    if (req.method === 'POST' && url.pathname === '/save-placements') {
      const data = await readBody(req);
      const body =
        '// GENERATED by the tile editor (editor.html) — the single home for everything\n' +
        '// placed on a map, keyed by subregion id:\n' +
        '//   { subId: { decor:  [{ key, x, y, w, h, rot }],\n' +
        '//              monsters:[{ x, y, id? }],   loot:    [{ x, y, item? }],\n' +
        '//              boss:    [{ x, y }],        miniboss:[{ x, y }] } }\n' +
        '// A monster/loot with no id/item rolls from the region table at load; a\n' +
        '// pinned id/item is authored here. decor is cosmetic. Safe to hand-edit.\n' +
        `export const PLACEMENTS = ${JSON.stringify(data, null, 2)};\n`;
      await writeFile(join(root, 'data', 'placements.js'), body);
      // Keep the readable dump in step with every save, from the just-saved
      // placements and the current (possibly edited-this-session) geometry.
      const zones = await freshZones();
      await writeFile(join(root, 'data', 'maps.txt'), renderText(data, null, zones) + '\n');
      await writeFile(join(root, 'data', 'maps.json'), JSON.stringify(manifests(data, null, zones), null, 2) + '\n');
      return json(res, { ok: true, regions: Object.keys(data).length });
    }
    // Persist base-map geometry edits (paint mode) back into zones.js — the one
    // source of truth for map layout. Body is { subId: [rowString, …] }.
    if (req.method === 'POST' && url.pathname === '/save-map') {
      const data = await readBody(req);
      const zonesPath = join(root, 'data', 'zones.js');
      try {
        let source = await readFile(zonesPath, 'utf8');
        for (const id of Object.keys(data)) source = rewriteZonesMap(source, id, data[id]);
        await writeFile(zonesPath, source);
      } catch (e) {
        return json(res, { ok: false, error: String(e.message || e) }, 400);
      }
      // Re-read the freshly written geometry + current placements for the dumps.
      const zones = await freshZones();
      const placements = await freshPlacements();
      await writeFile(join(root, 'data', 'maps.txt'), renderText(placements, null, zones) + '\n');
      await writeFile(join(root, 'data', 'maps.json'), JSON.stringify(manifests(placements, null, zones), null, 2) + '\n');
      return json(res, { ok: true, regions: Object.keys(data).length });
    }
    if (req.method === 'GET' && url.pathname === '/sheets') {
      const files = (await readdir(join(root, 'art'))).filter((f) => f.endsWith('.png')).sort();
      return json(res, files);
    }
    if (req.method === 'GET' && url.pathname === '/tiles') {
      const files = (await readdir(join(root, 'assets', 'tiles')))
        .filter((f) => f.endsWith('.png'))
        .map((f) => f.replace(/\.png$/, ''))
        .sort();
      return json(res, files);
    }
    if (req.method === 'POST' && url.pathname === '/detect') {
      const { sheet } = await readBody(req);
      const out = await runSlicer([join('art', basename(sheet)), '--detect', '--json']);
      return json(res, { ok: true, boxes: JSON.parse(out) });
    }
    if (req.method === 'POST' && url.pathname === '/slice') {
      const { sheet, name, box, tags = [] } = await readBody(req);
      const nm = safeName(name);
      if (!nm || !Array.isArray(box) || box.length !== 4) return json(res, { ok: false, error: 'bad name/box' }, 400);
      const out = await runSlicer([
        join('art', basename(sheet)), '--name', nm, '--box', box.map((n) => Math.round(n)).join(','),
        '--tags', tags.join(','),
      ]);
      return json(res, JSON.parse(out.trim().split('\n').pop()));
    }

    let path = normalize(decodeURIComponent(url.pathname)).replace(/^([/\\])+/, '');
    if (path === '' || path.endsWith('/')) path += 'index.html';
    const file = join(root, path);
    if (!file.startsWith(root)) throw new Error('outside root');
    const body = await readFile(file);
    res.writeHead(200, {
      'Content-Type': TYPES[extname(file)] ?? 'application/octet-stream',
      'Cache-Control': 'no-store',
    });
    res.end(body);
  } catch {
    res.writeHead(404, { 'Content-Type': 'text/plain' });
    res.end('not found');
  }
}).listen(port, '127.0.0.1', () => {
  console.log(`Red Dragon Labyrinth dev server: http://localhost:${port}/ (caching disabled, localhost-only)`);
  if (process.argv.includes('--open')) {
    const url = `http://localhost:${port}/editor.html`;
    const opener = process.platform === 'darwin' ? 'open' : process.platform === 'win32' ? 'start' : 'xdg-open';
    try { spawn(opener, [url], { stdio: 'ignore', detached: true }).unref(); } catch {}
    console.log(`opening the tile editor → ${url}`);
  }
});
